channels:
  - pytorch
  - defaults
dependencies:
  - pytest
  - pytest-cov
  - pytest-mock
  - pip
  - libpng
  - jpeg
  - ca-certificates
  - h5py # [x86_64 and (not win or py <= 39)]
  - pip:
    - future
    - pillow >=5.3.0, !=8.3.*
    - scipy
    - av
    - dataclasses
